### ISSUE TITLE
몬티홀 함수명 정하기

### ISSUE THREAD

**Issue by jhy0285** [BEBE-Git/Monty-Hall-Game#4]
## Description
몬티홀 문제를 해결할 함수명을 정하겠습니다

## Todo
- [ ] 파이썬 함수명 컨벤션 확인하기
- [ ] 몬티홀 문제 해결 함수명 고민하기
- [ ] 몬티홀 문제 해결 함수명 확정하기

## Riviewer
이수빈 님이 봐주세요
